version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing workspace dependencies..."
      - npm ci
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
      - echo "API URL:" && echo $VITE_API_URL
  
  build:
    commands:
      - echo "Building admin frontend application..."
      - cd admin-frontend
      - npm run build
      - echo "Build completed successfully"
  
  post_build:
    commands:
      - echo "Syncing to S3..."
      - cd admin-frontend
      - |
        aws s3 sync dist/ s3://${S3_BUCKET}/ \
          --delete \
          --cache-control "public, max-age=31536000, immutable" \
          --exclude "index.html" \
          --exclude "*.html"
      - |
        aws s3 sync dist/ s3://${S3_BUCKET}/ \
          --exclude "*" \
          --include "*.html" \
          --cache-control "public, max-age=0, must-revalidate"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - echo "Admin frontend deployment completed"

artifacts:
  files:
    - '**/*'
  base-directory: admin-frontend/dist
  name: admin-frontend-build

cache:
  paths:
    - 'node_modules/**/*'
    - 'admin-frontend/node_modules/**/*'
    - 'shared/node_modules/**/*'
