version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing backend dependencies..."
      - cd backend
      - npm ci
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
  
  build:
    commands:
      - echo "Building backend application..."
      - npm run build
      - echo "Build completed successfully"
  
  post_build:
    commands:
      - echo "Preparing deployment artifacts..."
      - cd backend
      - echo "Backend build completed"

artifacts:
  files:
    - backend/dist/**/*
    - backend/node_modules/**/*
    - backend/package.json
    - appspec.yml
    - scripts/**/*
  name: backend-build

cache:
  paths:
    - 'backend/node_modules/**/*'
