version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm ci
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
  
  build:
    commands:
      - echo "Building frontend application..."
      - npm run build
      - echo "Build completed successfully"
  
  post_build:
    commands:
      - echo "Syncing to S3..."
      - |
        aws s3 sync dist/ s3://resistance-radio-website-dev-734110488556/ \
          --delete \
          --cache-control "public, max-age=31536000, immutable" \
          --exclude "index.html" \
          --exclude "*.html"
      - |
        aws s3 sync dist/ s3://resistance-radio-website-dev-734110488556/ \
          --exclude "*" \
          --include "*.html" \
          --cache-control "public, max-age=0, must-revalidate"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id EYKP4STY3RIHX --paths "/*"
      - echo "Frontend deployment completed"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
  name: frontend-build

cache:
  paths:
    - 'frontend/node_modules/**/*'
