import { useState, useEffect } from 'react';

interface OptimizedImageProps {
  src: string;
  alt: string;
  width?: number;
  height?: number;
  className?: string;
  loading?: 'lazy' | 'eager';
  sizes?: string;
}

/**
 * Optimized image component with lazy loading and responsive images
 * Generates srcset for different screen sizes
 */
export default function OptimizedImage({
  src,
  alt,
  width,
  height,
  className = '',
  loading = 'lazy',
  sizes = '100vw'
}: OptimizedImageProps) {
  const [isLoaded, setIsLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);

  // Generate srcset for responsive images
  const generateSrcSet = (imageSrc: string): string => {
    // If it's an external URL, return as is
    if (imageSrc.startsWith('http')) {
      return imageSrc;
    }

    // For local images, generate different sizes
    // In production, these would be generated by a build tool or CDN
    const widths = [320, 640, 768, 1024, 1280, 1920];
    const srcset = widths
      .map(w => `${imageSrc}?w=${w} ${w}w`)
      .join(', ');
    
    return srcset;
  };

  useEffect(() => {
    // Preload image
    const img = new Image();
    img.src = src;
    img.onload = () => setIsLoaded(true);
    img.onerror = () => setHasError(true);
  }, [src]);

  if (hasError) {
    return (
      <div 
        className={`image-placeholder ${className}`}
        style={{
          width: width || '100%',
          height: height || 'auto',
          background: '#f0f0f0',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#999'
        }}
      >
        <span>Image not available</span>
      </div>
    );
  }

  return (
    <img
      src={src}
      srcSet={generateSrcSet(src)}
      sizes={sizes}
      alt={alt}
      width={width}
      height={height}
      className={`${className} ${isLoaded ? 'loaded' : 'loading'}`}
      loading={loading}
      decoding="async"
      style={{
        opacity: isLoaded ? 1 : 0,
        transition: 'opacity 0.3s ease-in-out'
      }}
      onLoad={() => setIsLoaded(true)}
      onError={() => setHasError(true)}
    />
  );
}
